package com.cfecweb.leon.shared;

import java.io.Serializable;

// Generated Mar 25, 2010 8:46:23 AM by Hibernate Tools 3.2.4.GA

/**
 * ArenewVesselsId generated by hbm2java
 */
@SuppressWarnings("serial")
public class ArenewVesselsId implements Serializable {

	private String cfecid;
	private String ryear;
	private String adfg;

	public ArenewVesselsId() {
	}

	public ArenewVesselsId(String cfecid, String ryear, String adfg) {
		this.cfecid = cfecid;
		this.ryear = ryear;
		this.adfg = adfg;
	}

	public String getCfecid() {
		return this.cfecid;
	}

	public void setCfecid(String cfecid) {
		this.cfecid = cfecid;
	}

	public String getRyear() {
		return this.ryear;
	}

	public void setRyear(String ryear) {
		this.ryear = ryear;
	}

	public String getAdfg() {
		return this.adfg;
	}

	public void setAdfg(String adfg) {
		this.adfg = adfg;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ArenewVesselsId))
			return false;
		ArenewVesselsId castOther = (ArenewVesselsId) other;

		return ((this.getCfecid() == castOther.getCfecid()) || (this
				.getCfecid() != null
				&& castOther.getCfecid() != null && this.getCfecid().equals(
				castOther.getCfecid())))
				&& ((this.getRyear() == castOther.getRyear()) || (this
						.getRyear() != null
						&& castOther.getRyear() != null && this.getRyear()
						.equals(castOther.getRyear())))
				&& ((this.getAdfg() == castOther.getAdfg()) || (this.getAdfg() != null
						&& castOther.getAdfg() != null && this.getAdfg()
						.equals(castOther.getAdfg())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getCfecid() == null ? 0 : this.getCfecid().hashCode());
		result = 37 * result
				+ (getRyear() == null ? 0 : this.getRyear().hashCode());
		result = 37 * result
				+ (getAdfg() == null ? 0 : this.getAdfg().hashCode());
		return result;
	}

    @Override
    public String toString() {
        return "ArenewVesselsId{" +
                "cfecid='" + cfecid + '\'' +
                ", ryear='" + ryear + '\'' +
                ", adfg='" + adfg + '\'' +
                '}';
    }
}
