package com.cfecweb.leon.shared;

import java.io.Serializable;

// Generated Mar 25, 2010 8:46:23 AM by Hibernate Tools 3.2.4.GA

/**
 * ArenewChangesId generated by hbm2java
 */
@SuppressWarnings("serial")
public class ArenewChangesId implements Serializable {

	private String seq;
	private String attribute;
	private String confirmcode;

	public ArenewChangesId() {
	}

	public ArenewChangesId(String seq, String attribute, String confirmcode) {
		this.seq = seq;
		this.attribute = attribute;
		this.confirmcode = confirmcode;
	}

	public String getSeq() {
		return this.seq;
	}

	public void setSeq(String seq) {
		this.seq = seq;
	}

	public String getAttribute() {
		return this.attribute;
	}

	public void setAttribute(String attribute) {
		this.attribute = attribute;
	}

	public String getConfirmcode() {
		return this.confirmcode;
	}

	public void setConfirmcode(String confirmcode) {
		this.confirmcode = confirmcode;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ArenewChangesId))
			return false;
		ArenewChangesId castOther = (ArenewChangesId) other;

		return ((this.getSeq() == castOther.getSeq()) || (this.getSeq() != null
				&& castOther.getSeq() != null && this.getSeq().equals(
				castOther.getSeq())))
				&& ((this.getAttribute() == castOther.getAttribute()) || (this
						.getAttribute() != null
						&& castOther.getAttribute() != null && this
						.getAttribute().equals(castOther.getAttribute())))
				&& ((this.getConfirmcode() == castOther.getConfirmcode()) || (this
						.getConfirmcode() != null
						&& castOther.getConfirmcode() != null && this
						.getConfirmcode().equals(castOther.getConfirmcode())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getSeq() == null ? 0 : this.getSeq().hashCode());
		result = 37 * result
				+ (getAttribute() == null ? 0 : this.getAttribute().hashCode());
		result = 37
				* result
				+ (getConfirmcode() == null ? 0 : this.getConfirmcode()
						.hashCode());
		return result;
	}

    @Override
    public String toString() {
        return "ArenewChangesId{" +
                "seq='" + seq + '\'' +
                ", attribute='" + attribute + '\'' +
                ", confirmcode='" + confirmcode + '\'' +
                '}';
    }
}
