package com.cfecweb.leon.shared;

// Generated Mar 25, 2010 8:46:23 AM by Hibernate Tools 3.2.4.GA

import java.io.Serializable;
import java.util.Date;

/**
 * ArenewChanges generated by hbm2java
 */
@SuppressWarnings({ "serial", "rawtypes" })
public class ArenewChanges implements Serializable, Comparable {

	private ArenewChangesId id;
	private ArenewEntity arenewEntity;
	private ArenewPayment arenewPayment;
	private String type;
	private String oldvalue;
	private String newvalue;
	private Date updatedate;
	private String object;

	public ArenewChanges() {
	}

	public ArenewChanges(ArenewChangesId id, ArenewEntity arenewEntity,
			ArenewPayment arenewPayment, String type, Date updatedate) {
		this.id = id;
		this.arenewEntity = arenewEntity;
		this.arenewPayment = arenewPayment;
		this.type = type;
		this.updatedate = updatedate;
	}

	public ArenewChanges(ArenewChangesId id, ArenewEntity arenewEntity,
			ArenewPayment arenewPayment, String type, String oldvalue,
			String newvalue, Date updatedate, String object) {
		this.id = id;
		this.arenewEntity = arenewEntity;
		this.arenewPayment = arenewPayment;
		this.type = type;
		this.oldvalue = oldvalue;
		this.newvalue = newvalue;
		this.updatedate = updatedate;
		this.object = object;
	}

	public ArenewChangesId getId() {
		return this.id;
	}

	public void setId(ArenewChangesId id) {
		this.id = id;
	}

	public ArenewEntity getArenewEntity() {
		return this.arenewEntity;
	}

	public void setArenewEntity(ArenewEntity arenewEntity) {
		this.arenewEntity = arenewEntity;
	}

	public ArenewPayment getArenewPayment() {
		return this.arenewPayment;
	}

	public void setArenewPayment(ArenewPayment arenewPayment) {
		this.arenewPayment = arenewPayment;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getOldvalue() {
		return this.oldvalue;
	}

	public void setOldvalue(String oldvalue) {
		this.oldvalue = oldvalue;
	}

	public String getNewvalue() {
		return this.newvalue;
	}

	public void setNewvalue(String newvalue) {
		this.newvalue = newvalue;
	}

	public Date getUpdatedate() {
		return this.updatedate;
	}

	public void setUpdatedate(Date updatedate) {
		this.updatedate = updatedate;
	}

	public String getObject() {
		return this.object;
	}

	public void setObject(String object) {
		this.object = object;
	}
	
	public int compareTo(Object cadd) {
		ArenewChanges chg = null;
		try {
		chg = (ArenewChanges) cadd;
		/*
		 * This is a sort feature for return permit list. It compares Vessel Names first, 
		 * then lastnames, and organizes the list to be easier to read. Even though we
		 * are in the BbPermit class, the search is organized by the Misc object, since
		 * at times it is possible for a person to be on a different vessel than the one
		 * that was originally registered with the permit.
		 */
		
		if (this.getType().equalsIgnoreCase(chg.getType())) {
			return this.getId().getAttribute().compareTo(chg.getId().getAttribute());
		} else {
			return this.getId().getAttribute().compareTo(chg.getId().getAttribute());
		}
		} catch (Exception e) {
			/*Print out error message to Stout because we have no logging*/
			//System.out.println("Sorry Ty no logging in BbPermit.java ");
			e.printStackTrace();
			//System.out.println(bb);
			System.out.println(this);
		} finally {
					
		}
		return 0;
	}

}
