package com.cfecweb.leon.shared;

// Generated Mar 25, 2010 8:46:23 AM by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * PeopleViewId generated by hbm2java
 */
@SuppressWarnings("serial")
public class PeopleViewId implements java.io.Serializable {

	private String idNumber;
	private String personsName;
	private String nameType;
	private Date birthDate;
	private Date deathDate;
	private String balanceFlag;
	private Integer arrearageAmount;
	private Integer memoArrearageAmount;
	private Integer holdRefundAmount;
	private Integer refundAmount;
	private Date refundOkDate;
	private String phoneNumber;
	private String unlistedPhoneFlag;
	private String alienFlag;
	private String seeFileFlag;
	private String suspendFlag;
	private Date suspendDate;
	private String fileNumber;
	private String fileOutFlag;
	private Date fileOutDate;
	private String fileOutLocation;
	private String addressResidencyFlag;
	private String addressType;
	private String addressStreet;
	private String addressCity;
	private String addressState;
	private String addressPostalCode;
	private String addressCountry;
	private String personLastName;
	private String personFirstName;

	public PeopleViewId() {
	}

	public PeopleViewId(String idNumber, String personsName, String nameType,
			Date birthDate, Date deathDate, String balanceFlag,
			Integer arrearageAmount, Integer memoArrearageAmount,
			Integer holdRefundAmount, Integer refundAmount, Date refundOkDate,
			String phoneNumber, String unlistedPhoneFlag, String alienFlag,
			String seeFileFlag, String suspendFlag, Date suspendDate,
			String fileNumber, String fileOutFlag, Date fileOutDate,
			String fileOutLocation, String addressResidencyFlag,
			String addressType, String addressStreet, String addressCity,
			String addressState, String addressPostalCode,
			String addressCountry, String personLastName, String personFirstName) {
		this.idNumber = idNumber;
		this.personsName = personsName;
		this.nameType = nameType;
		this.birthDate = birthDate;
		this.deathDate = deathDate;
		this.balanceFlag = balanceFlag;
		this.arrearageAmount = arrearageAmount;
		this.memoArrearageAmount = memoArrearageAmount;
		this.holdRefundAmount = holdRefundAmount;
		this.refundAmount = refundAmount;
		this.refundOkDate = refundOkDate;
		this.phoneNumber = phoneNumber;
		this.unlistedPhoneFlag = unlistedPhoneFlag;
		this.alienFlag = alienFlag;
		this.seeFileFlag = seeFileFlag;
		this.suspendFlag = suspendFlag;
		this.suspendDate = suspendDate;
		this.fileNumber = fileNumber;
		this.fileOutFlag = fileOutFlag;
		this.fileOutDate = fileOutDate;
		this.fileOutLocation = fileOutLocation;
		this.addressResidencyFlag = addressResidencyFlag;
		this.addressType = addressType;
		this.addressStreet = addressStreet;
		this.addressCity = addressCity;
		this.addressState = addressState;
		this.addressPostalCode = addressPostalCode;
		this.addressCountry = addressCountry;
		this.personLastName = personLastName;
		this.personFirstName = personFirstName;
	}

	public String getIdNumber() {
		return this.idNumber;
	}

	public void setIdNumber(String idNumber) {
		this.idNumber = idNumber;
	}

	public String getPersonsName() {
		return this.personsName;
	}

	public void setPersonsName(String personsName) {
		this.personsName = personsName;
	}

	public String getNameType() {
		return this.nameType;
	}

	public void setNameType(String nameType) {
		this.nameType = nameType;
	}

	public Date getBirthDate() {
		return this.birthDate;
	}

	public void setBirthDate(Date birthDate) {
		this.birthDate = birthDate;
	}

	public Date getDeathDate() {
		return this.deathDate;
	}

	public void setDeathDate(Date deathDate) {
		this.deathDate = deathDate;
	}

	public String getBalanceFlag() {
		return this.balanceFlag;
	}

	public void setBalanceFlag(String balanceFlag) {
		this.balanceFlag = balanceFlag;
	}

	public Integer getArrearageAmount() {
		return this.arrearageAmount;
	}

	public void setArrearageAmount(Integer arrearageAmount) {
		this.arrearageAmount = arrearageAmount;
	}

	public Integer getMemoArrearageAmount() {
		return this.memoArrearageAmount;
	}

	public void setMemoArrearageAmount(Integer memoArrearageAmount) {
		this.memoArrearageAmount = memoArrearageAmount;
	}

	public Integer getHoldRefundAmount() {
		return this.holdRefundAmount;
	}

	public void setHoldRefundAmount(Integer holdRefundAmount) {
		this.holdRefundAmount = holdRefundAmount;
	}

	public Integer getRefundAmount() {
		return this.refundAmount;
	}

	public void setRefundAmount(Integer refundAmount) {
		this.refundAmount = refundAmount;
	}

	public Date getRefundOkDate() {
		return this.refundOkDate;
	}

	public void setRefundOkDate(Date refundOkDate) {
		this.refundOkDate = refundOkDate;
	}

	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	public String getUnlistedPhoneFlag() {
		return this.unlistedPhoneFlag;
	}

	public void setUnlistedPhoneFlag(String unlistedPhoneFlag) {
		this.unlistedPhoneFlag = unlistedPhoneFlag;
	}

	public String getAlienFlag() {
		return this.alienFlag;
	}

	public void setAlienFlag(String alienFlag) {
		this.alienFlag = alienFlag;
	}

	public String getSeeFileFlag() {
		return this.seeFileFlag;
	}

	public void setSeeFileFlag(String seeFileFlag) {
		this.seeFileFlag = seeFileFlag;
	}

	public String getSuspendFlag() {
		return this.suspendFlag;
	}

	public void setSuspendFlag(String suspendFlag) {
		this.suspendFlag = suspendFlag;
	}

	public Date getSuspendDate() {
		return this.suspendDate;
	}

	public void setSuspendDate(Date suspendDate) {
		this.suspendDate = suspendDate;
	}

	public String getFileNumber() {
		return this.fileNumber;
	}

	public void setFileNumber(String fileNumber) {
		this.fileNumber = fileNumber;
	}

	public String getFileOutFlag() {
		return this.fileOutFlag;
	}

	public void setFileOutFlag(String fileOutFlag) {
		this.fileOutFlag = fileOutFlag;
	}

	public Date getFileOutDate() {
		return this.fileOutDate;
	}

	public void setFileOutDate(Date fileOutDate) {
		this.fileOutDate = fileOutDate;
	}

	public String getFileOutLocation() {
		return this.fileOutLocation;
	}

	public void setFileOutLocation(String fileOutLocation) {
		this.fileOutLocation = fileOutLocation;
	}

	public String getAddressResidencyFlag() {
		return this.addressResidencyFlag;
	}

	public void setAddressResidencyFlag(String addressResidencyFlag) {
		this.addressResidencyFlag = addressResidencyFlag;
	}

	public String getAddressType() {
		return this.addressType;
	}

	public void setAddressType(String addressType) {
		this.addressType = addressType;
	}

	public String getAddressStreet() {
		return this.addressStreet;
	}

	public void setAddressStreet(String addressStreet) {
		this.addressStreet = addressStreet;
	}

	public String getAddressCity() {
		return this.addressCity;
	}

	public void setAddressCity(String addressCity) {
		this.addressCity = addressCity;
	}

	public String getAddressState() {
		return this.addressState;
	}

	public void setAddressState(String addressState) {
		this.addressState = addressState;
	}

	public String getAddressPostalCode() {
		return this.addressPostalCode;
	}

	public void setAddressPostalCode(String addressPostalCode) {
		this.addressPostalCode = addressPostalCode;
	}

	public String getAddressCountry() {
		return this.addressCountry;
	}

	public void setAddressCountry(String addressCountry) {
		this.addressCountry = addressCountry;
	}

	public String getPersonLastName() {
		return this.personLastName;
	}

	public void setPersonLastName(String personLastName) {
		this.personLastName = personLastName;
	}

	public String getPersonFirstName() {
		return this.personFirstName;
	}

	public void setPersonFirstName(String personFirstName) {
		this.personFirstName = personFirstName;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PeopleViewId))
			return false;
		PeopleViewId castOther = (PeopleViewId) other;

		return ((this.getIdNumber() == castOther.getIdNumber()) || (this
				.getIdNumber() != null
				&& castOther.getIdNumber() != null && this.getIdNumber()
				.equals(castOther.getIdNumber())))
				&& ((this.getPersonsName() == castOther.getPersonsName()) || (this
						.getPersonsName() != null
						&& castOther.getPersonsName() != null && this
						.getPersonsName().equals(castOther.getPersonsName())))
				&& ((this.getNameType() == castOther.getNameType()) || (this
						.getNameType() != null
						&& castOther.getNameType() != null && this
						.getNameType().equals(castOther.getNameType())))
				&& ((this.getBirthDate() == castOther.getBirthDate()) || (this
						.getBirthDate() != null
						&& castOther.getBirthDate() != null && this
						.getBirthDate().equals(castOther.getBirthDate())))
				&& ((this.getDeathDate() == castOther.getDeathDate()) || (this
						.getDeathDate() != null
						&& castOther.getDeathDate() != null && this
						.getDeathDate().equals(castOther.getDeathDate())))
				&& ((this.getBalanceFlag() == castOther.getBalanceFlag()) || (this
						.getBalanceFlag() != null
						&& castOther.getBalanceFlag() != null && this
						.getBalanceFlag().equals(castOther.getBalanceFlag())))
				&& ((this.getArrearageAmount() == castOther
						.getArrearageAmount()) || (this.getArrearageAmount() != null
						&& castOther.getArrearageAmount() != null && this
						.getArrearageAmount().equals(
								castOther.getArrearageAmount())))
				&& ((this.getMemoArrearageAmount() == castOther
						.getMemoArrearageAmount()) || (this
						.getMemoArrearageAmount() != null
						&& castOther.getMemoArrearageAmount() != null && this
						.getMemoArrearageAmount().equals(
								castOther.getMemoArrearageAmount())))
				&& ((this.getHoldRefundAmount() == castOther
						.getHoldRefundAmount()) || (this.getHoldRefundAmount() != null
						&& castOther.getHoldRefundAmount() != null && this
						.getHoldRefundAmount().equals(
								castOther.getHoldRefundAmount())))
				&& ((this.getRefundAmount() == castOther.getRefundAmount()) || (this
						.getRefundAmount() != null
						&& castOther.getRefundAmount() != null && this
						.getRefundAmount().equals(castOther.getRefundAmount())))
				&& ((this.getRefundOkDate() == castOther.getRefundOkDate()) || (this
						.getRefundOkDate() != null
						&& castOther.getRefundOkDate() != null && this
						.getRefundOkDate().equals(castOther.getRefundOkDate())))
				&& ((this.getPhoneNumber() == castOther.getPhoneNumber()) || (this
						.getPhoneNumber() != null
						&& castOther.getPhoneNumber() != null && this
						.getPhoneNumber().equals(castOther.getPhoneNumber())))
				&& ((this.getUnlistedPhoneFlag() == castOther
						.getUnlistedPhoneFlag()) || (this
						.getUnlistedPhoneFlag() != null
						&& castOther.getUnlistedPhoneFlag() != null && this
						.getUnlistedPhoneFlag().equals(
								castOther.getUnlistedPhoneFlag())))
				&& ((this.getAlienFlag() == castOther.getAlienFlag()) || (this
						.getAlienFlag() != null
						&& castOther.getAlienFlag() != null && this
						.getAlienFlag().equals(castOther.getAlienFlag())))
				&& ((this.getSeeFileFlag() == castOther.getSeeFileFlag()) || (this
						.getSeeFileFlag() != null
						&& castOther.getSeeFileFlag() != null && this
						.getSeeFileFlag().equals(castOther.getSeeFileFlag())))
				&& ((this.getSuspendFlag() == castOther.getSuspendFlag()) || (this
						.getSuspendFlag() != null
						&& castOther.getSuspendFlag() != null && this
						.getSuspendFlag().equals(castOther.getSuspendFlag())))
				&& ((this.getSuspendDate() == castOther.getSuspendDate()) || (this
						.getSuspendDate() != null
						&& castOther.getSuspendDate() != null && this
						.getSuspendDate().equals(castOther.getSuspendDate())))
				&& ((this.getFileNumber() == castOther.getFileNumber()) || (this
						.getFileNumber() != null
						&& castOther.getFileNumber() != null && this
						.getFileNumber().equals(castOther.getFileNumber())))
				&& ((this.getFileOutFlag() == castOther.getFileOutFlag()) || (this
						.getFileOutFlag() != null
						&& castOther.getFileOutFlag() != null && this
						.getFileOutFlag().equals(castOther.getFileOutFlag())))
				&& ((this.getFileOutDate() == castOther.getFileOutDate()) || (this
						.getFileOutDate() != null
						&& castOther.getFileOutDate() != null && this
						.getFileOutDate().equals(castOther.getFileOutDate())))
				&& ((this.getFileOutLocation() == castOther
						.getFileOutLocation()) || (this.getFileOutLocation() != null
						&& castOther.getFileOutLocation() != null && this
						.getFileOutLocation().equals(
								castOther.getFileOutLocation())))
				&& ((this.getAddressResidencyFlag() == castOther
						.getAddressResidencyFlag()) || (this
						.getAddressResidencyFlag() != null
						&& castOther.getAddressResidencyFlag() != null && this
						.getAddressResidencyFlag().equals(
								castOther.getAddressResidencyFlag())))
				&& ((this.getAddressType() == castOther.getAddressType()) || (this
						.getAddressType() != null
						&& castOther.getAddressType() != null && this
						.getAddressType().equals(castOther.getAddressType())))
				&& ((this.getAddressStreet() == castOther.getAddressStreet()) || (this
						.getAddressStreet() != null
						&& castOther.getAddressStreet() != null && this
						.getAddressStreet()
						.equals(castOther.getAddressStreet())))
				&& ((this.getAddressCity() == castOther.getAddressCity()) || (this
						.getAddressCity() != null
						&& castOther.getAddressCity() != null && this
						.getAddressCity().equals(castOther.getAddressCity())))
				&& ((this.getAddressState() == castOther.getAddressState()) || (this
						.getAddressState() != null
						&& castOther.getAddressState() != null && this
						.getAddressState().equals(castOther.getAddressState())))
				&& ((this.getAddressPostalCode() == castOther
						.getAddressPostalCode()) || (this
						.getAddressPostalCode() != null
						&& castOther.getAddressPostalCode() != null && this
						.getAddressPostalCode().equals(
								castOther.getAddressPostalCode())))
				&& ((this.getAddressCountry() == castOther.getAddressCountry()) || (this
						.getAddressCountry() != null
						&& castOther.getAddressCountry() != null && this
						.getAddressCountry().equals(
								castOther.getAddressCountry())))
				&& ((this.getPersonLastName() == castOther.getPersonLastName()) || (this
						.getPersonLastName() != null
						&& castOther.getPersonLastName() != null && this
						.getPersonLastName().equals(
								castOther.getPersonLastName())))
				&& ((this.getPersonFirstName() == castOther
						.getPersonFirstName()) || (this.getPersonFirstName() != null
						&& castOther.getPersonFirstName() != null && this
						.getPersonFirstName().equals(
								castOther.getPersonFirstName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getIdNumber() == null ? 0 : this.getIdNumber().hashCode());
		result = 37
				* result
				+ (getPersonsName() == null ? 0 : this.getPersonsName()
						.hashCode());
		result = 37 * result
				+ (getNameType() == null ? 0 : this.getNameType().hashCode());
		result = 37 * result
				+ (getBirthDate() == null ? 0 : this.getBirthDate().hashCode());
		result = 37 * result
				+ (getDeathDate() == null ? 0 : this.getDeathDate().hashCode());
		result = 37
				* result
				+ (getBalanceFlag() == null ? 0 : this.getBalanceFlag()
						.hashCode());
		result = 37
				* result
				+ (getArrearageAmount() == null ? 0 : this.getArrearageAmount()
						.hashCode());
		result = 37
				* result
				+ (getMemoArrearageAmount() == null ? 0 : this
						.getMemoArrearageAmount().hashCode());
		result = 37
				* result
				+ (getHoldRefundAmount() == null ? 0 : this
						.getHoldRefundAmount().hashCode());
		result = 37
				* result
				+ (getRefundAmount() == null ? 0 : this.getRefundAmount()
						.hashCode());
		result = 37
				* result
				+ (getRefundOkDate() == null ? 0 : this.getRefundOkDate()
						.hashCode());
		result = 37
				* result
				+ (getPhoneNumber() == null ? 0 : this.getPhoneNumber()
						.hashCode());
		result = 37
				* result
				+ (getUnlistedPhoneFlag() == null ? 0 : this
						.getUnlistedPhoneFlag().hashCode());
		result = 37 * result
				+ (getAlienFlag() == null ? 0 : this.getAlienFlag().hashCode());
		result = 37
				* result
				+ (getSeeFileFlag() == null ? 0 : this.getSeeFileFlag()
						.hashCode());
		result = 37
				* result
				+ (getSuspendFlag() == null ? 0 : this.getSuspendFlag()
						.hashCode());
		result = 37
				* result
				+ (getSuspendDate() == null ? 0 : this.getSuspendDate()
						.hashCode());
		result = 37
				* result
				+ (getFileNumber() == null ? 0 : this.getFileNumber()
						.hashCode());
		result = 37
				* result
				+ (getFileOutFlag() == null ? 0 : this.getFileOutFlag()
						.hashCode());
		result = 37
				* result
				+ (getFileOutDate() == null ? 0 : this.getFileOutDate()
						.hashCode());
		result = 37
				* result
				+ (getFileOutLocation() == null ? 0 : this.getFileOutLocation()
						.hashCode());
		result = 37
				* result
				+ (getAddressResidencyFlag() == null ? 0 : this
						.getAddressResidencyFlag().hashCode());
		result = 37
				* result
				+ (getAddressType() == null ? 0 : this.getAddressType()
						.hashCode());
		result = 37
				* result
				+ (getAddressStreet() == null ? 0 : this.getAddressStreet()
						.hashCode());
		result = 37
				* result
				+ (getAddressCity() == null ? 0 : this.getAddressCity()
						.hashCode());
		result = 37
				* result
				+ (getAddressState() == null ? 0 : this.getAddressState()
						.hashCode());
		result = 37
				* result
				+ (getAddressPostalCode() == null ? 0 : this
						.getAddressPostalCode().hashCode());
		result = 37
				* result
				+ (getAddressCountry() == null ? 0 : this.getAddressCountry()
						.hashCode());
		result = 37
				* result
				+ (getPersonLastName() == null ? 0 : this.getPersonLastName()
						.hashCode());
		result = 37
				* result
				+ (getPersonFirstName() == null ? 0 : this.getPersonFirstName()
						.hashCode());
		return result;
	}

}
