package com.cfecweb.leon.shared;

// Generated Mar 25, 2010 8:46:23 AM by Hibernate Tools 3.2.4.GA

/**
 * PeopleView generated by hbm2java
 */
@SuppressWarnings("serial")
public class PeopleView implements java.io.Serializable {

	private PeopleViewId id;

	public PeopleView() {
	}

	public PeopleView(PeopleViewId id) {
		this.id = id;
	}

	public PeopleViewId getId() {
		return this.id;
	}

	public void setId(PeopleViewId id) {
		this.id = id;
	}

}
