package com.cfecweb.leon.shared;

import java.io.Serializable;

// Generated Mar 25, 2010 8:46:23 AM by Hibernate Tools 3.2.4.GA

/**
 * RenewFisheryId generated by hbm2java
 */
@SuppressWarnings("serial")
public class RenewFisheryId implements Serializable {

	private String fishery;
	private String resfee;
	private String nonresfee;
	private String respovertyfee;
	private String nonrespovertyfee;
	private String description;
	private String status;
	private String year;

	public RenewFisheryId() {
	}

	public RenewFisheryId(String fishery, String resfee, String nonresfee,
			String respovertyfee, String nonrespovertyfee, String description,
			String status, String year) {
		this.fishery = fishery;
		this.resfee = resfee;
		this.nonresfee = nonresfee;
		this.respovertyfee = respovertyfee;
		this.nonrespovertyfee = nonrespovertyfee;
		this.description = description;
		this.status = status;
		this.year = year;
	}

	public String getFishery() {
		return this.fishery;
	}

	public void setFishery(String fishery) {
		this.fishery = fishery;
	}

	public String getResfee() {
		return this.resfee;
	}

	public void setResfee(String resfee) {
		this.resfee = resfee;
	}

	public String getNonresfee() {
		return this.nonresfee;
	}

	public void setNonresfee(String nonresfee) {
		this.nonresfee = nonresfee;
	}

	public String getRespovertyfee() {
		return this.respovertyfee;
	}

	public void setRespovertyfee(String respovertyfee) {
		this.respovertyfee = respovertyfee;
	}

	public String getNonrespovertyfee() {
		return this.nonrespovertyfee;
	}

	public void setNonrespovertyfee(String nonrespovertyfee) {
		this.nonrespovertyfee = nonrespovertyfee;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}	

	public String getYear() {
		return year;
	}

	public void setYear(String year) {
		this.year = year;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RenewFisheryId))
			return false;
		RenewFisheryId castOther = (RenewFisheryId) other;

		return ((this.getFishery() == castOther.getFishery()) || (this
				.getFishery() != null
				&& castOther.getFishery() != null && this.getFishery().equals(
				castOther.getFishery())))
				&& ((this.getResfee() == castOther.getResfee()) || (this
						.getResfee() != null
						&& castOther.getResfee() != null && this.getResfee()
						.equals(castOther.getResfee())))
				&& ((this.getNonresfee() == castOther.getNonresfee()) || (this
						.getNonresfee() != null
						&& castOther.getNonresfee() != null && this
						.getNonresfee().equals(castOther.getNonresfee())))
				&& ((this.getRespovertyfee() == castOther.getRespovertyfee()) || (this
						.getRespovertyfee() != null
						&& castOther.getRespovertyfee() != null && this
						.getRespovertyfee()
						.equals(castOther.getRespovertyfee())))
				&& ((this.getNonrespovertyfee() == castOther
						.getNonrespovertyfee()) || (this.getNonrespovertyfee() != null
						&& castOther.getNonrespovertyfee() != null && this
						.getNonrespovertyfee().equals(
								castOther.getNonrespovertyfee())))
				&& ((this.getDescription() == castOther.getDescription()) || (this
						.getDescription() != null
						&& castOther.getDescription() != null && this
						.getDescription().equals(castOther.getDescription())))
				&& ((this.getStatus() == castOther.getStatus()) || (this
						.getStatus() != null
						&& castOther.getStatus() != null && this.getStatus()
						.equals(castOther.getStatus())))
				&& ((this.getYear() == castOther.getYear()) || (this
						.getYear() != null
						&& castOther.getYear() != null && this.getYear()
						.equals(castOther.getYear())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getFishery() == null ? 0 : this.getFishery().hashCode());
		result = 37 * result
				+ (getResfee() == null ? 0 : this.getResfee().hashCode());
		result = 37 * result
				+ (getNonresfee() == null ? 0 : this.getNonresfee().hashCode());
		result = 37
				* result
				+ (getRespovertyfee() == null ? 0 : this.getRespovertyfee()
						.hashCode());
		result = 37
				* result
				+ (getNonrespovertyfee() == null ? 0 : this
						.getNonrespovertyfee().hashCode());
		result = 37
				* result
				+ (getDescription() == null ? 0 : this.getDescription()
						.hashCode());
		result = 37 * result
				+ (getStatus() == null ? 0 : this.getStatus().hashCode());
		result = 37 * result
				+ (getYear() == null ? 0 : this.getYear().hashCode());
		return result;
	}

}
