package com.cfecweb.leon.shared;

import java.io.Serializable;

// Generated Mar 25, 2010 8:46:23 AM by Hibernate Tools 3.2.4.GA

/**
 * RenewFishery generated by hbm2java
 */
@SuppressWarnings("serial")
public class RenewFishery implements Serializable {

	private RenewFisheryId id;

	public RenewFishery() {
	}

	public RenewFishery(RenewFisheryId id) {
		this.id = id;
	}

	public RenewFisheryId getId() {
		return this.id;
	}

	public void setId(RenewFisheryId id) {
		this.id = id;
	}
	
	public int compareTo(Object fadd) {
		RenewFishery fshy = null;
		try {
			fshy = (RenewFishery) fadd;
		/*
		 * This is a sort feature for return permit list. It compares Fisheries first, 
		 * then Permit Year, and organizes the list to be easier to read.
		 */
		
		if (this.getId().getFishery().equalsIgnoreCase(fshy.getId().getFishery())) {
			return this.getId().getFishery().compareTo(fshy.getId().getFishery());
		}
		
		//return this.getId().getFishery().compareTo(pmt.getId().getFishery());
		} catch (Exception e) {
			/*Print out error message to Stout because we have no logging*/
			//System.out.println("Sorry Ty no logging in BbPermit.java ");
			e.printStackTrace();
			//System.out.println(bb);
			System.out.println(this);
		} finally {
					
		}
		return 0;
	}

}
