package com.cfecweb.leon.shared;

import java.io.Serializable;

// Generated Mar 25, 2010 8:46:23 AM by Hibernate Tools 3.2.4.GA

/**
 * RnwEntityId generated by hbm2java
 */
@SuppressWarnings("serial")
public class RnwEntityId implements Serializable {

	private String permitHolderId;
	private String permitHolderPhone;
	private String permitHolderFileNumber;
	private String residencyCode;
	private String addressStreet;
	private String addressCity;
	private String addressState;
	private String addressPostalCode;
	private String addressCountry;
	private String XRenewalYear;
	private String XLfisname;
	private String XFilsname;
	private String XEstaterep;
	private String XUnlisted;
	private String linkStatus;
	private String XDifferentialCurrent;
	private String XDifferentialPast;
	private String XDifferentialPast2;

	public RnwEntityId() {
	}

	public RnwEntityId(String permitHolderId, String permitHolderPhone,
			String permitHolderFileNumber, String residencyCode,
			String addressStreet, String addressCity, String addressState,
			String addressPostalCode, String addressCountry,
			String XRenewalYear, String XLfisname, String XFilsname,
			String XEstaterep, String XUnlisted, String linkStatus,
			String XDifferentialCurrent, String XDifferentialPast,
			String XDifferentialPast2) {
		this.permitHolderId = permitHolderId;
		this.permitHolderPhone = permitHolderPhone;
		this.permitHolderFileNumber = permitHolderFileNumber;
		this.residencyCode = residencyCode;
		this.addressStreet = addressStreet;
		this.addressCity = addressCity;
		this.addressState = addressState;
		this.addressPostalCode = addressPostalCode;
		this.addressCountry = addressCountry;
		this.XRenewalYear = XRenewalYear;
		this.XLfisname = XLfisname;
		this.XFilsname = XFilsname;
		this.XEstaterep = XEstaterep;
		this.XUnlisted = XUnlisted;
		this.linkStatus = linkStatus;
		this.XDifferentialCurrent = XDifferentialCurrent;
		this.XDifferentialPast = XDifferentialPast;
		this.XDifferentialPast2 = XDifferentialPast2;
	}

	public String getPermitHolderId() {
		return this.permitHolderId;
	}

	public void setPermitHolderId(String permitHolderId) {
		this.permitHolderId = permitHolderId;
	}

	public String getPermitHolderPhone() {
		return this.permitHolderPhone;
	}

	public void setPermitHolderPhone(String permitHolderPhone) {
		this.permitHolderPhone = permitHolderPhone;
	}

	public String getPermitHolderFileNumber() {
		return this.permitHolderFileNumber;
	}

	public void setPermitHolderFileNumber(String permitHolderFileNumber) {
		this.permitHolderFileNumber = permitHolderFileNumber;
	}

	public String getResidencyCode() {
		return this.residencyCode;
	}

	public void setResidencyCode(String residencyCode) {
		this.residencyCode = residencyCode;
	}

	public String getAddressStreet() {
		return this.addressStreet;
	}

	public void setAddressStreet(String addressStreet) {
		this.addressStreet = addressStreet;
	}

	public String getAddressCity() {
		return this.addressCity;
	}

	public void setAddressCity(String addressCity) {
		this.addressCity = addressCity;
	}

	public String getAddressState() {
		return this.addressState;
	}

	public void setAddressState(String addressState) {
		this.addressState = addressState;
	}

	public String getAddressPostalCode() {
		return this.addressPostalCode;
	}

	public void setAddressPostalCode(String addressPostalCode) {
		this.addressPostalCode = addressPostalCode;
	}

	public String getAddressCountry() {
		return this.addressCountry;
	}

	public void setAddressCountry(String addressCountry) {
		this.addressCountry = addressCountry;
	}

	public String getXRenewalYear() {
		return this.XRenewalYear;
	}

	public void setXRenewalYear(String XRenewalYear) {
		this.XRenewalYear = XRenewalYear;
	}

	public String getXLfisname() {
		return this.XLfisname;
	}

	public void setXLfisname(String XLfisname) {
		this.XLfisname = XLfisname;
	}

	public String getXFilsname() {
		return this.XFilsname;
	}

	public void setXFilsname(String XFilsname) {
		this.XFilsname = XFilsname;
	}

	public String getXEstaterep() {
		return this.XEstaterep;
	}

	public void setXEstaterep(String XEstaterep) {
		this.XEstaterep = XEstaterep;
	}

	public String getXUnlisted() {
		return this.XUnlisted;
	}

	public void setXUnlisted(String XUnlisted) {
		this.XUnlisted = XUnlisted;
	}

	public String getLinkStatus() {
		return this.linkStatus;
	}

	public void setLinkStatus(String linkStatus) {
		this.linkStatus = linkStatus;
	}

	public String getXDifferentialCurrent() {
		return this.XDifferentialCurrent;
	}

	public void setXDifferentialCurrent(String XDifferentialCurrent) {
		this.XDifferentialCurrent = XDifferentialCurrent;
	}

	public String getXDifferentialPast() {
		return this.XDifferentialPast;
	}

	public void setXDifferentialPast(String XDifferentialPast) {
		this.XDifferentialPast = XDifferentialPast;
	}

	public String getXDifferentialPast2() {
		return this.XDifferentialPast2;
	}

	public void setXDifferentialPast2(String XDifferentialPast2) {
		this.XDifferentialPast2 = XDifferentialPast2;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RnwEntityId))
			return false;
		RnwEntityId castOther = (RnwEntityId) other;

		return ((this.getPermitHolderId() == castOther.getPermitHolderId()) || (this
				.getPermitHolderId() != null
				&& castOther.getPermitHolderId() != null && this
				.getPermitHolderId().equals(castOther.getPermitHolderId())))
				&& ((this.getPermitHolderPhone() == castOther
						.getPermitHolderPhone()) || (this
						.getPermitHolderPhone() != null
						&& castOther.getPermitHolderPhone() != null && this
						.getPermitHolderPhone().equals(
								castOther.getPermitHolderPhone())))
				&& ((this.getPermitHolderFileNumber() == castOther
						.getPermitHolderFileNumber()) || (this
						.getPermitHolderFileNumber() != null
						&& castOther.getPermitHolderFileNumber() != null && this
						.getPermitHolderFileNumber().equals(
								castOther.getPermitHolderFileNumber())))
				&& ((this.getResidencyCode() == castOther.getResidencyCode()) || (this
						.getResidencyCode() != null
						&& castOther.getResidencyCode() != null && this
						.getResidencyCode()
						.equals(castOther.getResidencyCode())))
				&& ((this.getAddressStreet() == castOther.getAddressStreet()) || (this
						.getAddressStreet() != null
						&& castOther.getAddressStreet() != null && this
						.getAddressStreet()
						.equals(castOther.getAddressStreet())))
				&& ((this.getAddressCity() == castOther.getAddressCity()) || (this
						.getAddressCity() != null
						&& castOther.getAddressCity() != null && this
						.getAddressCity().equals(castOther.getAddressCity())))
				&& ((this.getAddressState() == castOther.getAddressState()) || (this
						.getAddressState() != null
						&& castOther.getAddressState() != null && this
						.getAddressState().equals(castOther.getAddressState())))
				&& ((this.getAddressPostalCode() == castOther
						.getAddressPostalCode()) || (this
						.getAddressPostalCode() != null
						&& castOther.getAddressPostalCode() != null && this
						.getAddressPostalCode().equals(
								castOther.getAddressPostalCode())))
				&& ((this.getAddressCountry() == castOther.getAddressCountry()) || (this
						.getAddressCountry() != null
						&& castOther.getAddressCountry() != null && this
						.getAddressCountry().equals(
								castOther.getAddressCountry())))
				&& ((this.getXRenewalYear() == castOther.getXRenewalYear()) || (this
						.getXRenewalYear() != null
						&& castOther.getXRenewalYear() != null && this
						.getXRenewalYear().equals(castOther.getXRenewalYear())))
				&& ((this.getXLfisname() == castOther.getXLfisname()) || (this
						.getXLfisname() != null
						&& castOther.getXLfisname() != null && this
						.getXLfisname().equals(castOther.getXLfisname())))
				&& ((this.getXFilsname() == castOther.getXFilsname()) || (this
						.getXFilsname() != null
						&& castOther.getXFilsname() != null && this
						.getXFilsname().equals(castOther.getXFilsname())))
				&& ((this.getXEstaterep() == castOther.getXEstaterep()) || (this
						.getXEstaterep() != null
						&& castOther.getXEstaterep() != null && this
						.getXEstaterep().equals(castOther.getXEstaterep())))
				&& ((this.getXUnlisted() == castOther.getXUnlisted()) || (this
						.getXUnlisted() != null
						&& castOther.getXUnlisted() != null && this
						.getXUnlisted().equals(castOther.getXUnlisted())))
				&& ((this.getLinkStatus() == castOther.getLinkStatus()) || (this
						.getLinkStatus() != null
						&& castOther.getLinkStatus() != null && this
						.getLinkStatus().equals(castOther.getLinkStatus())))
				&& ((this.getXDifferentialCurrent() == castOther
						.getXDifferentialCurrent()) || (this
						.getXDifferentialCurrent() != null
						&& castOther.getXDifferentialCurrent() != null && this
						.getXDifferentialCurrent().equals(
								castOther.getXDifferentialCurrent())))
				&& ((this.getXDifferentialPast() == castOther
						.getXDifferentialPast()) || (this
						.getXDifferentialPast() != null
						&& castOther.getXDifferentialPast() != null && this
						.getXDifferentialPast().equals(
								castOther.getXDifferentialPast())))
				&& ((this.getXDifferentialPast2() == castOther
						.getXDifferentialPast2()) || (this
						.getXDifferentialPast2() != null
						&& castOther.getXDifferentialPast2() != null && this
						.getXDifferentialPast2().equals(
								castOther.getXDifferentialPast2())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getPermitHolderId() == null ? 0 : this.getPermitHolderId()
						.hashCode());
		result = 37
				* result
				+ (getPermitHolderPhone() == null ? 0 : this
						.getPermitHolderPhone().hashCode());
		result = 37
				* result
				+ (getPermitHolderFileNumber() == null ? 0 : this
						.getPermitHolderFileNumber().hashCode());
		result = 37
				* result
				+ (getResidencyCode() == null ? 0 : this.getResidencyCode()
						.hashCode());
		result = 37
				* result
				+ (getAddressStreet() == null ? 0 : this.getAddressStreet()
						.hashCode());
		result = 37
				* result
				+ (getAddressCity() == null ? 0 : this.getAddressCity()
						.hashCode());
		result = 37
				* result
				+ (getAddressState() == null ? 0 : this.getAddressState()
						.hashCode());
		result = 37
				* result
				+ (getAddressPostalCode() == null ? 0 : this
						.getAddressPostalCode().hashCode());
		result = 37
				* result
				+ (getAddressCountry() == null ? 0 : this.getAddressCountry()
						.hashCode());
		result = 37
				* result
				+ (getXRenewalYear() == null ? 0 : this.getXRenewalYear()
						.hashCode());
		result = 37 * result
				+ (getXLfisname() == null ? 0 : this.getXLfisname().hashCode());
		result = 37 * result
				+ (getXFilsname() == null ? 0 : this.getXFilsname().hashCode());
		result = 37
				* result
				+ (getXEstaterep() == null ? 0 : this.getXEstaterep()
						.hashCode());
		result = 37 * result
				+ (getXUnlisted() == null ? 0 : this.getXUnlisted().hashCode());
		result = 37
				* result
				+ (getLinkStatus() == null ? 0 : this.getLinkStatus()
						.hashCode());
		result = 37
				* result
				+ (getXDifferentialCurrent() == null ? 0 : this
						.getXDifferentialCurrent().hashCode());
		result = 37
				* result
				+ (getXDifferentialPast() == null ? 0 : this
						.getXDifferentialPast().hashCode());
		result = 37
				* result
				+ (getXDifferentialPast2() == null ? 0 : this
						.getXDifferentialPast2().hashCode());
		return result;
	}

}
