package com.cfecweb.leon.shared;

import java.io.Serializable;

// Generated Mar 25, 2010 8:46:23 AM by Hibernate Tools 3.2.4.GA

/**
 * RnwEntity generated by hbm2java
 */
@SuppressWarnings("serial")
public class RnwEntity implements Serializable {

	private RnwEntityId id;

	public RnwEntity() {
	}

	public RnwEntity(RnwEntityId id) {
		this.id = id;
	}

	public RnwEntityId getId() {
		return this.id;
	}

	public void setId(RnwEntityId id) {
		this.id = id;
	}

}
