package com.cfecweb.leon.shared;

// Generated Mar 25, 2010 8:46:23 AM by Hibernate Tools 3.2.4.GA

import java.io.Serializable;

/**
 * RnwPmtId generated by hbm2java
 */
@SuppressWarnings("serial")
public class RnwPmtId implements Serializable {

	private String permitYear;
	private String permitSerialNumber;
	private String fisheryCode;
	private String permitType;
	private String permitHolderId;
	private String permitFeeType;
	private String permitAdfgNumber;
	private String permitHolderFileNumber;
	private String XDifferential;
	private Long FRfee;
	private Long FPfee;
	private String FLdesc;
	private String FSdesc;
	private Long XMsna;
	private String XNote;
	private String XRenewalYear;
	private String renewalStatus;
	private String confirmationCode;
	private String XMultipmts;

	public RnwPmtId() {
	}

	public RnwPmtId(String permitYear, String permitSerialNumber,
			String fisheryCode, String permitType, String permitHolderId,
			String permitFeeType, String permitAdfgNumber,
			String permitHolderFileNumber, String XDifferential,
			Long FRfee, Long FPfee, String FLdesc, String FSdesc,
			Long XMsna, String XNote, String XRenewalYear,
			String renewalStatus, String confirmationCode, String XMultipmts) {
		this.permitYear = permitYear;
		this.permitSerialNumber = permitSerialNumber;
		this.fisheryCode = fisheryCode;
		this.permitType = permitType;
		this.permitHolderId = permitHolderId;
		this.permitFeeType = permitFeeType;
		this.permitAdfgNumber = permitAdfgNumber;
		this.permitHolderFileNumber = permitHolderFileNumber;
		this.XDifferential = XDifferential;
		this.FRfee = FRfee;
		this.FPfee = FPfee;
		this.FLdesc = FLdesc;
		this.FSdesc = FSdesc;
		this.XMsna = XMsna;
		this.XNote = XNote;
		this.XRenewalYear = XRenewalYear;
		this.renewalStatus = renewalStatus;
		this.confirmationCode = confirmationCode;
		this.XMultipmts = XMultipmts;
	}

	public String getPermitYear() {
		return this.permitYear;
	}

	public void setPermitYear(String permitYear) {
		this.permitYear = permitYear;
	}

	public String getPermitSerialNumber() {
		return this.permitSerialNumber;
	}

	public void setPermitSerialNumber(String permitSerialNumber) {
		this.permitSerialNumber = permitSerialNumber;
	}

	public String getFisheryCode() {
		return this.fisheryCode;
	}

	public void setFisheryCode(String fisheryCode) {
		this.fisheryCode = fisheryCode;
	}

	public String getPermitType() {
		return this.permitType;
	}

	public void setPermitType(String permitType) {
		this.permitType = permitType;
	}

	public String getPermitHolderId() {
		return this.permitHolderId;
	}

	public void setPermitHolderId(String permitHolderId) {
		this.permitHolderId = permitHolderId;
	}

	public String getPermitFeeType() {
		return this.permitFeeType;
	}

	public void setPermitFeeType(String permitFeeType) {
		this.permitFeeType = permitFeeType;
	}

	public String getPermitAdfgNumber() {
		return this.permitAdfgNumber;
	}

	public void setPermitAdfgNumber(String permitAdfgNumber) {
		this.permitAdfgNumber = permitAdfgNumber;
	}

	public String getPermitHolderFileNumber() {
		return this.permitHolderFileNumber;
	}

	public void setPermitHolderFileNumber(String permitHolderFileNumber) {
		this.permitHolderFileNumber = permitHolderFileNumber;
	}

	public String getXDifferential() {
		return this.XDifferential;
	}

	public void setXDifferential(String XDifferential) {
		this.XDifferential = XDifferential;
	}

	public Long getFRfee() {
		return this.FRfee;
	}

	public void setFRfee(Long FRfee) {
		this.FRfee = FRfee;
	}

	public Long getFPfee() {
		return this.FPfee;
	}

	public void setFPfee(Long FPfee) {
		this.FPfee = FPfee;
	}

	public String getFLdesc() {
		return this.FLdesc;
	}

	public void setFLdesc(String FLdesc) {
		this.FLdesc = FLdesc;
	}

	public String getFSdesc() {
		return this.FSdesc;
	}

	public void setFSdesc(String FSdesc) {
		this.FSdesc = FSdesc;
	}

	public Long getXMsna() {
		return this.XMsna;
	}

	public void setXMsna(Long XMsna) {
		this.XMsna = XMsna;
	}

	public String getXNote() {
		return this.XNote;
	}

	public void setXNote(String XNote) {
		this.XNote = XNote;
	}

	public String getXRenewalYear() {
		return this.XRenewalYear;
	}

	public void setXRenewalYear(String XRenewalYear) {
		this.XRenewalYear = XRenewalYear;
	}

	public String getRenewalStatus() {
		return this.renewalStatus;
	}

	public void setRenewalStatus(String renewalStatus) {
		this.renewalStatus = renewalStatus;
	}

	public String getConfirmationCode() {
		return this.confirmationCode;
	}

	public void setConfirmationCode(String confirmationCode) {
		this.confirmationCode = confirmationCode;
	}	

	public String getXMultipmts() {
		return XMultipmts;
	}

	public void setXMultipmts(String xMultipmts) {
		XMultipmts = xMultipmts;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RnwPmtId))
			return false;
		RnwPmtId castOther = (RnwPmtId) other;

		return ((this.getPermitYear() == castOther.getPermitYear()) || (this
				.getPermitYear() != null
				&& castOther.getPermitYear() != null && this.getPermitYear()
				.equals(castOther.getPermitYear())))
				&& ((this.getPermitSerialNumber() == castOther
						.getPermitSerialNumber()) || (this
						.getPermitSerialNumber() != null
						&& castOther.getPermitSerialNumber() != null && this
						.getPermitSerialNumber().equals(
								castOther.getPermitSerialNumber())))
				&& ((this.getFisheryCode() == castOther.getFisheryCode()) || (this
						.getFisheryCode() != null
						&& castOther.getFisheryCode() != null && this
						.getFisheryCode().equals(castOther.getFisheryCode())))
				&& ((this.getPermitType() == castOther.getPermitType()) || (this
						.getPermitType() != null
						&& castOther.getPermitType() != null && this
						.getPermitType().equals(castOther.getPermitType())))
				&& ((this.getPermitHolderId() == castOther.getPermitHolderId()) || (this
						.getPermitHolderId() != null
						&& castOther.getPermitHolderId() != null && this
						.getPermitHolderId().equals(
								castOther.getPermitHolderId())))
				&& ((this.getPermitFeeType() == castOther.getPermitFeeType()) || (this
						.getPermitFeeType() != null
						&& castOther.getPermitFeeType() != null && this
						.getPermitFeeType()
						.equals(castOther.getPermitFeeType())))
				&& ((this.getPermitAdfgNumber() == castOther
						.getPermitAdfgNumber()) || (this.getPermitAdfgNumber() != null
						&& castOther.getPermitAdfgNumber() != null && this
						.getPermitAdfgNumber().equals(
								castOther.getPermitAdfgNumber())))
				&& ((this.getPermitHolderFileNumber() == castOther
						.getPermitHolderFileNumber()) || (this
						.getPermitHolderFileNumber() != null
						&& castOther.getPermitHolderFileNumber() != null && this
						.getPermitHolderFileNumber().equals(
								castOther.getPermitHolderFileNumber())))
				&& ((this.getXDifferential() == castOther.getXDifferential()) || (this
						.getXDifferential() != null
						&& castOther.getXDifferential() != null && this
						.getXDifferential()
						.equals(castOther.getXDifferential())))
				&& ((this.getFRfee() == castOther.getFRfee()) || (this
						.getFRfee() != null
						&& castOther.getFRfee() != null && this.getFRfee()
						.equals(castOther.getFRfee())))
				&& ((this.getFPfee() == castOther.getFPfee()) || (this
						.getFPfee() != null
						&& castOther.getFPfee() != null && this.getFPfee()
						.equals(castOther.getFPfee())))
				&& ((this.getFLdesc() == castOther.getFLdesc()) || (this
						.getFLdesc() != null
						&& castOther.getFLdesc() != null && this.getFLdesc()
						.equals(castOther.getFLdesc())))
				&& ((this.getFSdesc() == castOther.getFSdesc()) || (this
						.getFSdesc() != null
						&& castOther.getFSdesc() != null && this.getFSdesc()
						.equals(castOther.getFSdesc())))
				&& ((this.getXMsna() == castOther.getXMsna()) || (this
						.getXMsna() != null
						&& castOther.getXMsna() != null && this.getXMsna()
						.equals(castOther.getXMsna())))
				&& ((this.getXNote() == castOther.getXNote()) || (this
						.getXNote() != null
						&& castOther.getXNote() != null && this.getXNote()
						.equals(castOther.getXNote())))
				&& ((this.getXRenewalYear() == castOther.getXRenewalYear()) || (this
						.getXRenewalYear() != null
						&& castOther.getXRenewalYear() != null && this
						.getXRenewalYear().equals(castOther.getXRenewalYear())))
				&& ((this.getRenewalStatus() == castOther.getRenewalStatus()) || (this
						.getRenewalStatus() != null
						&& castOther.getRenewalStatus() != null && this
						.getRenewalStatus()
						.equals(castOther.getRenewalStatus())))
				&& ((this.getConfirmationCode() == castOther
						.getConfirmationCode()) || (this.getConfirmationCode() != null
						&& castOther.getConfirmationCode() != null && this
						.getConfirmationCode().equals(
								castOther.getConfirmationCode())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getPermitYear() == null ? 0 : this.getPermitYear()
						.hashCode());
		result = 37
				* result
				+ (getPermitSerialNumber() == null ? 0 : this
						.getPermitSerialNumber().hashCode());
		result = 37
				* result
				+ (getFisheryCode() == null ? 0 : this.getFisheryCode()
						.hashCode());
		result = 37
				* result
				+ (getPermitType() == null ? 0 : this.getPermitType()
						.hashCode());
		result = 37
				* result
				+ (getPermitHolderId() == null ? 0 : this.getPermitHolderId()
						.hashCode());
		result = 37
				* result
				+ (getPermitFeeType() == null ? 0 : this.getPermitFeeType()
						.hashCode());
		result = 37
				* result
				+ (getPermitAdfgNumber() == null ? 0 : this
						.getPermitAdfgNumber().hashCode());
		result = 37
				* result
				+ (getPermitHolderFileNumber() == null ? 0 : this
						.getPermitHolderFileNumber().hashCode());
		result = 37
				* result
				+ (getXDifferential() == null ? 0 : this.getXDifferential()
						.hashCode());
		result = 37 * result
				+ (getFRfee() == null ? 0 : this.getFRfee().hashCode());
		result = 37 * result
				+ (getFPfee() == null ? 0 : this.getFPfee().hashCode());
		result = 37 * result
				+ (getFLdesc() == null ? 0 : this.getFLdesc().hashCode());
		result = 37 * result
				+ (getFSdesc() == null ? 0 : this.getFSdesc().hashCode());
		result = 37 * result
				+ (getXMsna() == null ? 0 : this.getXMsna().hashCode());
		result = 37 * result
				+ (getXNote() == null ? 0 : this.getXNote().hashCode());
		result = 37
				* result
				+ (getXRenewalYear() == null ? 0 : this.getXRenewalYear()
						.hashCode());
		result = 37
				* result
				+ (getRenewalStatus() == null ? 0 : this.getRenewalStatus()
						.hashCode());
		result = 37
				* result
				+ (getConfirmationCode() == null ? 0 : this
						.getConfirmationCode().hashCode());
		return result;
	}

}
