package com.cfecweb.leon.shared;

import java.io.Serializable;

// Generated Mar 25, 2010 8:46:23 AM by Hibernate Tools 3.2.4.GA

/**
 * RnwPmt generated by hbm2java
 */
@SuppressWarnings("serial")
public class RnwPmt implements Serializable {

	private RnwPmtId id;

	public RnwPmt() {
	}

	public RnwPmt(RnwPmtId id) {
		this.id = id;
	}

	public RnwPmtId getId() {
		return this.id;
	}

	public void setId(RnwPmtId id) {
		this.id = id;
	}

}
