package com.cfecweb.leon.shared;

import java.io.Serializable;

// Generated Mar 25, 2010 8:46:23 AM by Hibernate Tools 3.2.4.GA

/**
 * RnwVes generated by hbm2java
 */
@SuppressWarnings("serial")
public class RnwVes implements Serializable {

	private RnwVesId id;

	public RnwVes() {
	}

	public RnwVes(RnwVesId id) {
		this.id = id;
	}

	public RnwVesId getId() {
		return this.id;
	}

	public void setId(RnwVesId id) {
		this.id = id;
	}

}
