package com.cfecweb.leon.shared;

// Generated Mar 25, 2010 8:46:23 AM by Hibernate Tools 3.2.4.GA

import java.io.Serializable;
import java.util.Date;

/**
 * RnwVesId generated by hbm2java
 */
@SuppressWarnings("serial")
public class RnwVesId implements Serializable {

	private String vesselYear;
	private String adfgNumber;
	private Long yearBuilt;
	private Long lengthFeet;
	private Long lengthInches;
	private String lengthVerified;
	private Long grossTons;
	private Long netTons;
	private Long horsepower;
	private String make;
	private String refrigerationFlag;
	private String engineType;
	private String hullType;
	private Long holdTankCapacity;
	private Long liveTankCapacity;
	private Long fuelCapacity;
	private Long value;
	private String freezerCannerFlag;
	private String tenderPackerFlag;
	private String charterBoatFlag;
	private String fishingBoatFlag;
	private String purseSeineFlag;
	private String beachSeineFlag;
	private String driftGillnetFlag;
	private String setGillnetFlag;
	private String handTrollFlag;
	private String longlineFlag;
	private String singleOtterTrawlFlag;
	private String fishwheelFlag;
	private String potGearFlag;
	private String ringNetFlag;
	private String diveGearFlag;
	private String powerTrollFlag;
	private String beamTrawlFlag;
	private String dredgeFlag;
	private String dinglebarFlag;
	private String jigFlag;
	private String doubleOtterTrawl;
	private String hearingGillnetFlag;
	private String pairTrawlFlag;
	private String otherGearFlag;
	private String homeportCity;
	private String homeportState;
	private String registrationType;
	private String coastGuardNumber;
	private String vesselName;
	private String foreignFlagIndicator;
	private String hullId;
	private String salmonTrollReg;
	private Date salmonTrollDate;
	private String salmonRegArea;
	private String permitSerial1;
	private String permitSerial2;
	private String permitHolderFileNumber;
	private String transporterFlag;
	private Long FRfee;
	private String XRenewalYear;
	private String renewalStatus;
	private String confirmationCode;

	public RnwVesId() {
	}

	public RnwVesId(String vesselYear, String adfgNumber, Long yearBuilt,
			Long lengthFeet, Long lengthInches,
			String lengthVerified, Long grossTons, Long netTons,
			Long horsepower, String make, String refrigerationFlag,
			String engineType, String hullType, Long holdTankCapacity,
			Long liveTankCapacity, Long fuelCapacity,
			Long value, String freezerCannerFlag,
			String tenderPackerFlag, String charterBoatFlag,
			String fishingBoatFlag, String purseSeineFlag,
			String beachSeineFlag, String driftGillnetFlag,
			String setGillnetFlag, String handTrollFlag, String longlineFlag,
			String singleOtterTrawlFlag, String fishwheelFlag,
			String potGearFlag, String ringNetFlag, String diveGearFlag,
			String powerTrollFlag, String beamTrawlFlag, String dredgeFlag,
			String dinglebarFlag, String jigFlag, String doubleOtterTrawl,
			String hearingGillnetFlag, String pairTrawlFlag,
			String otherGearFlag, String homeportCity, String homeportState,
			String registrationType, String coastGuardNumber,
			String vesselName, String foreignFlagIndicator, String hullId,
			String salmonTrollReg, Date salmonTrollDate, String salmonRegArea,
			String permitSerial1, String permitSerial2,
			String permitHolderFileNumber, String transporterFlag,
			Long FRfee, String XRenewalYear, String renewalStatus,
			String confirmationCode) {
		this.vesselYear = vesselYear;
		this.adfgNumber = adfgNumber;
		this.yearBuilt = yearBuilt;
		this.lengthFeet = lengthFeet;
		this.lengthInches = lengthInches;
		this.lengthVerified = lengthVerified;
		this.grossTons = grossTons;
		this.netTons = netTons;
		this.horsepower = horsepower;
		this.make = make;
		this.refrigerationFlag = refrigerationFlag;
		this.engineType = engineType;
		this.hullType = hullType;
		this.holdTankCapacity = holdTankCapacity;
		this.liveTankCapacity = liveTankCapacity;
		this.fuelCapacity = fuelCapacity;
		this.value = value;
		this.freezerCannerFlag = freezerCannerFlag;
		this.tenderPackerFlag = tenderPackerFlag;
		this.charterBoatFlag = charterBoatFlag;
		this.fishingBoatFlag = fishingBoatFlag;
		this.purseSeineFlag = purseSeineFlag;
		this.beachSeineFlag = beachSeineFlag;
		this.driftGillnetFlag = driftGillnetFlag;
		this.setGillnetFlag = setGillnetFlag;
		this.handTrollFlag = handTrollFlag;
		this.longlineFlag = longlineFlag;
		this.singleOtterTrawlFlag = singleOtterTrawlFlag;
		this.fishwheelFlag = fishwheelFlag;
		this.potGearFlag = potGearFlag;
		this.ringNetFlag = ringNetFlag;
		this.diveGearFlag = diveGearFlag;
		this.powerTrollFlag = powerTrollFlag;
		this.beamTrawlFlag = beamTrawlFlag;
		this.dredgeFlag = dredgeFlag;
		this.dinglebarFlag = dinglebarFlag;
		this.jigFlag = jigFlag;
		this.doubleOtterTrawl = doubleOtterTrawl;
		this.hearingGillnetFlag = hearingGillnetFlag;
		this.pairTrawlFlag = pairTrawlFlag;
		this.otherGearFlag = otherGearFlag;
		this.homeportCity = homeportCity;
		this.homeportState = homeportState;
		this.registrationType = registrationType;
		this.coastGuardNumber = coastGuardNumber;
		this.vesselName = vesselName;
		this.foreignFlagIndicator = foreignFlagIndicator;
		this.hullId = hullId;
		this.salmonTrollReg = salmonTrollReg;
		this.salmonTrollDate = salmonTrollDate;
		this.salmonRegArea = salmonRegArea;
		this.permitSerial1 = permitSerial1;
		this.permitSerial2 = permitSerial2;
		this.permitHolderFileNumber = permitHolderFileNumber;
		this.transporterFlag = transporterFlag;
		this.FRfee = FRfee;
		this.XRenewalYear = XRenewalYear;
		this.renewalStatus = renewalStatus;
		this.confirmationCode = confirmationCode;
	}

	public String getVesselYear() {
		return this.vesselYear;
	}

	public void setVesselYear(String vesselYear) {
		this.vesselYear = vesselYear;
	}

	public String getAdfgNumber() {
		return this.adfgNumber;
	}

	public void setAdfgNumber(String adfgNumber) {
		this.adfgNumber = adfgNumber;
	}

	public Long getYearBuilt() {
		return this.yearBuilt;
	}

	public void setYearBuilt(Long yearBuilt) {
		this.yearBuilt = yearBuilt;
	}

	public Long getLengthFeet() {
		return this.lengthFeet;
	}

	public void setLengthFeet(Long lengthFeet) {
		this.lengthFeet = lengthFeet;
	}

	public Long getLengthInches() {
		return this.lengthInches;
	}

	public void setLengthInches(Long lengthInches) {
		this.lengthInches = lengthInches;
	}

	public String getLengthVerified() {
		return this.lengthVerified;
	}

	public void setLengthVerified(String lengthVerified) {
		this.lengthVerified = lengthVerified;
	}

	public Long getGrossTons() {
		return this.grossTons;
	}

	public void setGrossTons(Long grossTons) {
		this.grossTons = grossTons;
	}

	public Long getNetTons() {
		return this.netTons;
	}

	public void setNetTons(Long netTons) {
		this.netTons = netTons;
	}

	public Long getHorsepower() {
		return this.horsepower;
	}

	public void setHorsepower(Long horsepower) {
		this.horsepower = horsepower;
	}

	public String getMake() {
		return this.make;
	}

	public void setMake(String make) {
		this.make = make;
	}

	public String getRefrigerationFlag() {
		return this.refrigerationFlag;
	}

	public void setRefrigerationFlag(String refrigerationFlag) {
		this.refrigerationFlag = refrigerationFlag;
	}

	public String getEngineType() {
		return this.engineType;
	}

	public void setEngineType(String engineType) {
		this.engineType = engineType;
	}

	public String getHullType() {
		return this.hullType;
	}

	public void setHullType(String hullType) {
		this.hullType = hullType;
	}

	public Long getHoldTankCapacity() {
		return this.holdTankCapacity;
	}

	public void setHoldTankCapacity(Long holdTankCapacity) {
		this.holdTankCapacity = holdTankCapacity;
	}

	public Long getLiveTankCapacity() {
		return this.liveTankCapacity;
	}

	public void setLiveTankCapacity(Long liveTankCapacity) {
		this.liveTankCapacity = liveTankCapacity;
	}

	public Long getFuelCapacity() {
		return this.fuelCapacity;
	}

	public void setFuelCapacity(Long fuelCapacity) {
		this.fuelCapacity = fuelCapacity;
	}

	public Long getValue() {
		return this.value;
	}

	public void setValue(Long value) {
		this.value = value;
	}

	public String getFreezerCannerFlag() {
		return this.freezerCannerFlag;
	}

	public void setFreezerCannerFlag(String freezerCannerFlag) {
		this.freezerCannerFlag = freezerCannerFlag;
	}

	public String getTenderPackerFlag() {
		return this.tenderPackerFlag;
	}

	public void setTenderPackerFlag(String tenderPackerFlag) {
		this.tenderPackerFlag = tenderPackerFlag;
	}

	public String getCharterBoatFlag() {
		return this.charterBoatFlag;
	}

	public void setCharterBoatFlag(String charterBoatFlag) {
		this.charterBoatFlag = charterBoatFlag;
	}

	public String getFishingBoatFlag() {
		return this.fishingBoatFlag;
	}

	public void setFishingBoatFlag(String fishingBoatFlag) {
		this.fishingBoatFlag = fishingBoatFlag;
	}

	public String getPurseSeineFlag() {
		return this.purseSeineFlag;
	}

	public void setPurseSeineFlag(String purseSeineFlag) {
		this.purseSeineFlag = purseSeineFlag;
	}

	public String getBeachSeineFlag() {
		return this.beachSeineFlag;
	}

	public void setBeachSeineFlag(String beachSeineFlag) {
		this.beachSeineFlag = beachSeineFlag;
	}

	public String getDriftGillnetFlag() {
		return this.driftGillnetFlag;
	}

	public void setDriftGillnetFlag(String driftGillnetFlag) {
		this.driftGillnetFlag = driftGillnetFlag;
	}

	public String getSetGillnetFlag() {
		return this.setGillnetFlag;
	}

	public void setSetGillnetFlag(String setGillnetFlag) {
		this.setGillnetFlag = setGillnetFlag;
	}

	public String getHandTrollFlag() {
		return this.handTrollFlag;
	}

	public void setHandTrollFlag(String handTrollFlag) {
		this.handTrollFlag = handTrollFlag;
	}

	public String getLonglineFlag() {
		return this.longlineFlag;
	}

	public void setLonglineFlag(String longlineFlag) {
		this.longlineFlag = longlineFlag;
	}

	public String getSingleOtterTrawlFlag() {
		return this.singleOtterTrawlFlag;
	}

	public void setSingleOtterTrawlFlag(String singleOtterTrawlFlag) {
		this.singleOtterTrawlFlag = singleOtterTrawlFlag;
	}

	public String getFishwheelFlag() {
		return this.fishwheelFlag;
	}

	public void setFishwheelFlag(String fishwheelFlag) {
		this.fishwheelFlag = fishwheelFlag;
	}

	public String getPotGearFlag() {
		return this.potGearFlag;
	}

	public void setPotGearFlag(String potGearFlag) {
		this.potGearFlag = potGearFlag;
	}

	public String getRingNetFlag() {
		return this.ringNetFlag;
	}

	public void setRingNetFlag(String ringNetFlag) {
		this.ringNetFlag = ringNetFlag;
	}

	public String getDiveGearFlag() {
		return this.diveGearFlag;
	}

	public void setDiveGearFlag(String diveGearFlag) {
		this.diveGearFlag = diveGearFlag;
	}

	public String getPowerTrollFlag() {
		return this.powerTrollFlag;
	}

	public void setPowerTrollFlag(String powerTrollFlag) {
		this.powerTrollFlag = powerTrollFlag;
	}

	public String getBeamTrawlFlag() {
		return this.beamTrawlFlag;
	}

	public void setBeamTrawlFlag(String beamTrawlFlag) {
		this.beamTrawlFlag = beamTrawlFlag;
	}

	public String getDredgeFlag() {
		return this.dredgeFlag;
	}

	public void setDredgeFlag(String dredgeFlag) {
		this.dredgeFlag = dredgeFlag;
	}

	public String getDinglebarFlag() {
		return this.dinglebarFlag;
	}

	public void setDinglebarFlag(String dinglebarFlag) {
		this.dinglebarFlag = dinglebarFlag;
	}

	public String getJigFlag() {
		return this.jigFlag;
	}

	public void setJigFlag(String jigFlag) {
		this.jigFlag = jigFlag;
	}

	public String getDoubleOtterTrawl() {
		return this.doubleOtterTrawl;
	}

	public void setDoubleOtterTrawl(String doubleOtterTrawl) {
		this.doubleOtterTrawl = doubleOtterTrawl;
	}

	public String getHearingGillnetFlag() {
		return this.hearingGillnetFlag;
	}

	public void setHearingGillnetFlag(String hearingGillnetFlag) {
		this.hearingGillnetFlag = hearingGillnetFlag;
	}

	public String getPairTrawlFlag() {
		return this.pairTrawlFlag;
	}

	public void setPairTrawlFlag(String pairTrawlFlag) {
		this.pairTrawlFlag = pairTrawlFlag;
	}

	public String getOtherGearFlag() {
		return this.otherGearFlag;
	}

	public void setOtherGearFlag(String otherGearFlag) {
		this.otherGearFlag = otherGearFlag;
	}

	public String getHomeportCity() {
		return this.homeportCity;
	}

	public void setHomeportCity(String homeportCity) {
		this.homeportCity = homeportCity;
	}

	public String getHomeportState() {
		return this.homeportState;
	}

	public void setHomeportState(String homeportState) {
		this.homeportState = homeportState;
	}

	public String getRegistrationType() {
		return this.registrationType;
	}

	public void setRegistrationType(String registrationType) {
		this.registrationType = registrationType;
	}

	public String getCoastGuardNumber() {
		return this.coastGuardNumber;
	}

	public void setCoastGuardNumber(String coastGuardNumber) {
		this.coastGuardNumber = coastGuardNumber;
	}

	public String getVesselName() {
		return this.vesselName;
	}

	public void setVesselName(String vesselName) {
		this.vesselName = vesselName;
	}

	public String getForeignFlagIndicator() {
		return this.foreignFlagIndicator;
	}

	public void setForeignFlagIndicator(String foreignFlagIndicator) {
		this.foreignFlagIndicator = foreignFlagIndicator;
	}

	public String getHullId() {
		return this.hullId;
	}

	public void setHullId(String hullId) {
		this.hullId = hullId;
	}

	public String getSalmonTrollReg() {
		return this.salmonTrollReg;
	}

	public void setSalmonTrollReg(String salmonTrollReg) {
		this.salmonTrollReg = salmonTrollReg;
	}

	public Date getSalmonTrollDate() {
		return this.salmonTrollDate;
	}

	public void setSalmonTrollDate(Date salmonTrollDate) {
		this.salmonTrollDate = salmonTrollDate;
	}

	public String getSalmonRegArea() {
		return this.salmonRegArea;
	}

	public void setSalmonRegArea(String salmonRegArea) {
		this.salmonRegArea = salmonRegArea;
	}

	public String getPermitSerial1() {
		return this.permitSerial1;
	}

	public void setPermitSerial1(String permitSerial1) {
		this.permitSerial1 = permitSerial1;
	}

	public String getPermitSerial2() {
		return this.permitSerial2;
	}

	public void setPermitSerial2(String permitSerial2) {
		this.permitSerial2 = permitSerial2;
	}

	public String getPermitHolderFileNumber() {
		return this.permitHolderFileNumber;
	}

	public void setPermitHolderFileNumber(String permitHolderFileNumber) {
		this.permitHolderFileNumber = permitHolderFileNumber;
	}

	public String getTransporterFlag() {
		return this.transporterFlag;
	}

	public void setTransporterFlag(String transporterFlag) {
		this.transporterFlag = transporterFlag;
	}

	public Long getFRfee() {
		return this.FRfee;
	}

	public void setFRfee(Long FRfee) {
		this.FRfee = FRfee;
	}

	public String getXRenewalYear() {
		return this.XRenewalYear;
	}

	public void setXRenewalYear(String XRenewalYear) {
		this.XRenewalYear = XRenewalYear;
	}

	public String getRenewalStatus() {
		return this.renewalStatus;
	}

	public void setRenewalStatus(String renewalStatus) {
		this.renewalStatus = renewalStatus;
	}

	public String getConfirmationCode() {
		return this.confirmationCode;
	}

	public void setConfirmationCode(String confirmationCode) {
		this.confirmationCode = confirmationCode;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RnwVesId))
			return false;
		RnwVesId castOther = (RnwVesId) other;

		return ((this.getVesselYear() == castOther.getVesselYear()) || (this
				.getVesselYear() != null
				&& castOther.getVesselYear() != null && this.getVesselYear()
				.equals(castOther.getVesselYear())))
				&& ((this.getAdfgNumber() == castOther.getAdfgNumber()) || (this
						.getAdfgNumber() != null
						&& castOther.getAdfgNumber() != null && this
						.getAdfgNumber().equals(castOther.getAdfgNumber())))
				&& ((this.getYearBuilt() == castOther.getYearBuilt()) || (this
						.getYearBuilt() != null
						&& castOther.getYearBuilt() != null && this
						.getYearBuilt().equals(castOther.getYearBuilt())))
				&& ((this.getLengthFeet() == castOther.getLengthFeet()) || (this
						.getLengthFeet() != null
						&& castOther.getLengthFeet() != null && this
						.getLengthFeet().equals(castOther.getLengthFeet())))
				&& ((this.getLengthInches() == castOther.getLengthInches()) || (this
						.getLengthInches() != null
						&& castOther.getLengthInches() != null && this
						.getLengthInches().equals(castOther.getLengthInches())))
				&& ((this.getLengthVerified() == castOther.getLengthVerified()) || (this
						.getLengthVerified() != null
						&& castOther.getLengthVerified() != null && this
						.getLengthVerified().equals(
								castOther.getLengthVerified())))
				&& ((this.getGrossTons() == castOther.getGrossTons()) || (this
						.getGrossTons() != null
						&& castOther.getGrossTons() != null && this
						.getGrossTons().equals(castOther.getGrossTons())))
				&& ((this.getNetTons() == castOther.getNetTons()) || (this
						.getNetTons() != null
						&& castOther.getNetTons() != null && this.getNetTons()
						.equals(castOther.getNetTons())))
				&& ((this.getHorsepower() == castOther.getHorsepower()) || (this
						.getHorsepower() != null
						&& castOther.getHorsepower() != null && this
						.getHorsepower().equals(castOther.getHorsepower())))
				&& ((this.getMake() == castOther.getMake()) || (this.getMake() != null
						&& castOther.getMake() != null && this.getMake()
						.equals(castOther.getMake())))
				&& ((this.getRefrigerationFlag() == castOther
						.getRefrigerationFlag()) || (this
						.getRefrigerationFlag() != null
						&& castOther.getRefrigerationFlag() != null && this
						.getRefrigerationFlag().equals(
								castOther.getRefrigerationFlag())))
				&& ((this.getEngineType() == castOther.getEngineType()) || (this
						.getEngineType() != null
						&& castOther.getEngineType() != null && this
						.getEngineType().equals(castOther.getEngineType())))
				&& ((this.getHullType() == castOther.getHullType()) || (this
						.getHullType() != null
						&& castOther.getHullType() != null && this
						.getHullType().equals(castOther.getHullType())))
				&& ((this.getHoldTankCapacity() == castOther
						.getHoldTankCapacity()) || (this.getHoldTankCapacity() != null
						&& castOther.getHoldTankCapacity() != null && this
						.getHoldTankCapacity().equals(
								castOther.getHoldTankCapacity())))
				&& ((this.getLiveTankCapacity() == castOther
						.getLiveTankCapacity()) || (this.getLiveTankCapacity() != null
						&& castOther.getLiveTankCapacity() != null && this
						.getLiveTankCapacity().equals(
								castOther.getLiveTankCapacity())))
				&& ((this.getFuelCapacity() == castOther.getFuelCapacity()) || (this
						.getFuelCapacity() != null
						&& castOther.getFuelCapacity() != null && this
						.getFuelCapacity().equals(castOther.getFuelCapacity())))
				&& ((this.getValue() == castOther.getValue()) || (this
						.getValue() != null
						&& castOther.getValue() != null && this.getValue()
						.equals(castOther.getValue())))
				&& ((this.getFreezerCannerFlag() == castOther
						.getFreezerCannerFlag()) || (this
						.getFreezerCannerFlag() != null
						&& castOther.getFreezerCannerFlag() != null && this
						.getFreezerCannerFlag().equals(
								castOther.getFreezerCannerFlag())))
				&& ((this.getTenderPackerFlag() == castOther
						.getTenderPackerFlag()) || (this.getTenderPackerFlag() != null
						&& castOther.getTenderPackerFlag() != null && this
						.getTenderPackerFlag().equals(
								castOther.getTenderPackerFlag())))
				&& ((this.getCharterBoatFlag() == castOther
						.getCharterBoatFlag()) || (this.getCharterBoatFlag() != null
						&& castOther.getCharterBoatFlag() != null && this
						.getCharterBoatFlag().equals(
								castOther.getCharterBoatFlag())))
				&& ((this.getFishingBoatFlag() == castOther
						.getFishingBoatFlag()) || (this.getFishingBoatFlag() != null
						&& castOther.getFishingBoatFlag() != null && this
						.getFishingBoatFlag().equals(
								castOther.getFishingBoatFlag())))
				&& ((this.getPurseSeineFlag() == castOther.getPurseSeineFlag()) || (this
						.getPurseSeineFlag() != null
						&& castOther.getPurseSeineFlag() != null && this
						.getPurseSeineFlag().equals(
								castOther.getPurseSeineFlag())))
				&& ((this.getBeachSeineFlag() == castOther.getBeachSeineFlag()) || (this
						.getBeachSeineFlag() != null
						&& castOther.getBeachSeineFlag() != null && this
						.getBeachSeineFlag().equals(
								castOther.getBeachSeineFlag())))
				&& ((this.getDriftGillnetFlag() == castOther
						.getDriftGillnetFlag()) || (this.getDriftGillnetFlag() != null
						&& castOther.getDriftGillnetFlag() != null && this
						.getDriftGillnetFlag().equals(
								castOther.getDriftGillnetFlag())))
				&& ((this.getSetGillnetFlag() == castOther.getSetGillnetFlag()) || (this
						.getSetGillnetFlag() != null
						&& castOther.getSetGillnetFlag() != null && this
						.getSetGillnetFlag().equals(
								castOther.getSetGillnetFlag())))
				&& ((this.getHandTrollFlag() == castOther.getHandTrollFlag()) || (this
						.getHandTrollFlag() != null
						&& castOther.getHandTrollFlag() != null && this
						.getHandTrollFlag()
						.equals(castOther.getHandTrollFlag())))
				&& ((this.getLonglineFlag() == castOther.getLonglineFlag()) || (this
						.getLonglineFlag() != null
						&& castOther.getLonglineFlag() != null && this
						.getLonglineFlag().equals(castOther.getLonglineFlag())))
				&& ((this.getSingleOtterTrawlFlag() == castOther
						.getSingleOtterTrawlFlag()) || (this
						.getSingleOtterTrawlFlag() != null
						&& castOther.getSingleOtterTrawlFlag() != null && this
						.getSingleOtterTrawlFlag().equals(
								castOther.getSingleOtterTrawlFlag())))
				&& ((this.getFishwheelFlag() == castOther.getFishwheelFlag()) || (this
						.getFishwheelFlag() != null
						&& castOther.getFishwheelFlag() != null && this
						.getFishwheelFlag()
						.equals(castOther.getFishwheelFlag())))
				&& ((this.getPotGearFlag() == castOther.getPotGearFlag()) || (this
						.getPotGearFlag() != null
						&& castOther.getPotGearFlag() != null && this
						.getPotGearFlag().equals(castOther.getPotGearFlag())))
				&& ((this.getRingNetFlag() == castOther.getRingNetFlag()) || (this
						.getRingNetFlag() != null
						&& castOther.getRingNetFlag() != null && this
						.getRingNetFlag().equals(castOther.getRingNetFlag())))
				&& ((this.getDiveGearFlag() == castOther.getDiveGearFlag()) || (this
						.getDiveGearFlag() != null
						&& castOther.getDiveGearFlag() != null && this
						.getDiveGearFlag().equals(castOther.getDiveGearFlag())))
				&& ((this.getPowerTrollFlag() == castOther.getPowerTrollFlag()) || (this
						.getPowerTrollFlag() != null
						&& castOther.getPowerTrollFlag() != null && this
						.getPowerTrollFlag().equals(
								castOther.getPowerTrollFlag())))
				&& ((this.getBeamTrawlFlag() == castOther.getBeamTrawlFlag()) || (this
						.getBeamTrawlFlag() != null
						&& castOther.getBeamTrawlFlag() != null && this
						.getBeamTrawlFlag()
						.equals(castOther.getBeamTrawlFlag())))
				&& ((this.getDredgeFlag() == castOther.getDredgeFlag()) || (this
						.getDredgeFlag() != null
						&& castOther.getDredgeFlag() != null && this
						.getDredgeFlag().equals(castOther.getDredgeFlag())))
				&& ((this.getDinglebarFlag() == castOther.getDinglebarFlag()) || (this
						.getDinglebarFlag() != null
						&& castOther.getDinglebarFlag() != null && this
						.getDinglebarFlag()
						.equals(castOther.getDinglebarFlag())))
				&& ((this.getJigFlag() == castOther.getJigFlag()) || (this
						.getJigFlag() != null
						&& castOther.getJigFlag() != null && this.getJigFlag()
						.equals(castOther.getJigFlag())))
				&& ((this.getDoubleOtterTrawl() == castOther
						.getDoubleOtterTrawl()) || (this.getDoubleOtterTrawl() != null
						&& castOther.getDoubleOtterTrawl() != null && this
						.getDoubleOtterTrawl().equals(
								castOther.getDoubleOtterTrawl())))
				&& ((this.getHearingGillnetFlag() == castOther
						.getHearingGillnetFlag()) || (this
						.getHearingGillnetFlag() != null
						&& castOther.getHearingGillnetFlag() != null && this
						.getHearingGillnetFlag().equals(
								castOther.getHearingGillnetFlag())))
				&& ((this.getPairTrawlFlag() == castOther.getPairTrawlFlag()) || (this
						.getPairTrawlFlag() != null
						&& castOther.getPairTrawlFlag() != null && this
						.getPairTrawlFlag()
						.equals(castOther.getPairTrawlFlag())))
				&& ((this.getOtherGearFlag() == castOther.getOtherGearFlag()) || (this
						.getOtherGearFlag() != null
						&& castOther.getOtherGearFlag() != null && this
						.getOtherGearFlag()
						.equals(castOther.getOtherGearFlag())))
				&& ((this.getHomeportCity() == castOther.getHomeportCity()) || (this
						.getHomeportCity() != null
						&& castOther.getHomeportCity() != null && this
						.getHomeportCity().equals(castOther.getHomeportCity())))
				&& ((this.getHomeportState() == castOther.getHomeportState()) || (this
						.getHomeportState() != null
						&& castOther.getHomeportState() != null && this
						.getHomeportState()
						.equals(castOther.getHomeportState())))
				&& ((this.getRegistrationType() == castOther
						.getRegistrationType()) || (this.getRegistrationType() != null
						&& castOther.getRegistrationType() != null && this
						.getRegistrationType().equals(
								castOther.getRegistrationType())))
				&& ((this.getCoastGuardNumber() == castOther
						.getCoastGuardNumber()) || (this.getCoastGuardNumber() != null
						&& castOther.getCoastGuardNumber() != null && this
						.getCoastGuardNumber().equals(
								castOther.getCoastGuardNumber())))
				&& ((this.getVesselName() == castOther.getVesselName()) || (this
						.getVesselName() != null
						&& castOther.getVesselName() != null && this
						.getVesselName().equals(castOther.getVesselName())))
				&& ((this.getForeignFlagIndicator() == castOther
						.getForeignFlagIndicator()) || (this
						.getForeignFlagIndicator() != null
						&& castOther.getForeignFlagIndicator() != null && this
						.getForeignFlagIndicator().equals(
								castOther.getForeignFlagIndicator())))
				&& ((this.getHullId() == castOther.getHullId()) || (this
						.getHullId() != null
						&& castOther.getHullId() != null && this.getHullId()
						.equals(castOther.getHullId())))
				&& ((this.getSalmonTrollReg() == castOther.getSalmonTrollReg()) || (this
						.getSalmonTrollReg() != null
						&& castOther.getSalmonTrollReg() != null && this
						.getSalmonTrollReg().equals(
								castOther.getSalmonTrollReg())))
				&& ((this.getSalmonTrollDate() == castOther
						.getSalmonTrollDate()) || (this.getSalmonTrollDate() != null
						&& castOther.getSalmonTrollDate() != null && this
						.getSalmonTrollDate().equals(
								castOther.getSalmonTrollDate())))
				&& ((this.getSalmonRegArea() == castOther.getSalmonRegArea()) || (this
						.getSalmonRegArea() != null
						&& castOther.getSalmonRegArea() != null && this
						.getSalmonRegArea()
						.equals(castOther.getSalmonRegArea())))
				&& ((this.getPermitSerial1() == castOther.getPermitSerial1()) || (this
						.getPermitSerial1() != null
						&& castOther.getPermitSerial1() != null && this
						.getPermitSerial1()
						.equals(castOther.getPermitSerial1())))
				&& ((this.getPermitSerial2() == castOther.getPermitSerial2()) || (this
						.getPermitSerial2() != null
						&& castOther.getPermitSerial2() != null && this
						.getPermitSerial2()
						.equals(castOther.getPermitSerial2())))
				&& ((this.getPermitHolderFileNumber() == castOther
						.getPermitHolderFileNumber()) || (this
						.getPermitHolderFileNumber() != null
						&& castOther.getPermitHolderFileNumber() != null && this
						.getPermitHolderFileNumber().equals(
								castOther.getPermitHolderFileNumber())))
				&& ((this.getTransporterFlag() == castOther
						.getTransporterFlag()) || (this.getTransporterFlag() != null
						&& castOther.getTransporterFlag() != null && this
						.getTransporterFlag().equals(
								castOther.getTransporterFlag())))
				&& ((this.getFRfee() == castOther.getFRfee()) || (this
						.getFRfee() != null
						&& castOther.getFRfee() != null && this.getFRfee()
						.equals(castOther.getFRfee())))
				&& ((this.getXRenewalYear() == castOther.getXRenewalYear()) || (this
						.getXRenewalYear() != null
						&& castOther.getXRenewalYear() != null && this
						.getXRenewalYear().equals(castOther.getXRenewalYear())))
				&& ((this.getRenewalStatus() == castOther.getRenewalStatus()) || (this
						.getRenewalStatus() != null
						&& castOther.getRenewalStatus() != null && this
						.getRenewalStatus()
						.equals(castOther.getRenewalStatus())))
				&& ((this.getConfirmationCode() == castOther
						.getConfirmationCode()) || (this.getConfirmationCode() != null
						&& castOther.getConfirmationCode() != null && this
						.getConfirmationCode().equals(
								castOther.getConfirmationCode())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getVesselYear() == null ? 0 : this.getVesselYear()
						.hashCode());
		result = 37
				* result
				+ (getAdfgNumber() == null ? 0 : this.getAdfgNumber()
						.hashCode());
		result = 37 * result
				+ (getYearBuilt() == null ? 0 : this.getYearBuilt().hashCode());
		result = 37
				* result
				+ (getLengthFeet() == null ? 0 : this.getLengthFeet()
						.hashCode());
		result = 37
				* result
				+ (getLengthInches() == null ? 0 : this.getLengthInches()
						.hashCode());
		result = 37
				* result
				+ (getLengthVerified() == null ? 0 : this.getLengthVerified()
						.hashCode());
		result = 37 * result
				+ (getGrossTons() == null ? 0 : this.getGrossTons().hashCode());
		result = 37 * result
				+ (getNetTons() == null ? 0 : this.getNetTons().hashCode());
		result = 37
				* result
				+ (getHorsepower() == null ? 0 : this.getHorsepower()
						.hashCode());
		result = 37 * result
				+ (getMake() == null ? 0 : this.getMake().hashCode());
		result = 37
				* result
				+ (getRefrigerationFlag() == null ? 0 : this
						.getRefrigerationFlag().hashCode());
		result = 37
				* result
				+ (getEngineType() == null ? 0 : this.getEngineType()
						.hashCode());
		result = 37 * result
				+ (getHullType() == null ? 0 : this.getHullType().hashCode());
		result = 37
				* result
				+ (getHoldTankCapacity() == null ? 0 : this
						.getHoldTankCapacity().hashCode());
		result = 37
				* result
				+ (getLiveTankCapacity() == null ? 0 : this
						.getLiveTankCapacity().hashCode());
		result = 37
				* result
				+ (getFuelCapacity() == null ? 0 : this.getFuelCapacity()
						.hashCode());
		result = 37 * result
				+ (getValue() == null ? 0 : this.getValue().hashCode());
		result = 37
				* result
				+ (getFreezerCannerFlag() == null ? 0 : this
						.getFreezerCannerFlag().hashCode());
		result = 37
				* result
				+ (getTenderPackerFlag() == null ? 0 : this
						.getTenderPackerFlag().hashCode());
		result = 37
				* result
				+ (getCharterBoatFlag() == null ? 0 : this.getCharterBoatFlag()
						.hashCode());
		result = 37
				* result
				+ (getFishingBoatFlag() == null ? 0 : this.getFishingBoatFlag()
						.hashCode());
		result = 37
				* result
				+ (getPurseSeineFlag() == null ? 0 : this.getPurseSeineFlag()
						.hashCode());
		result = 37
				* result
				+ (getBeachSeineFlag() == null ? 0 : this.getBeachSeineFlag()
						.hashCode());
		result = 37
				* result
				+ (getDriftGillnetFlag() == null ? 0 : this
						.getDriftGillnetFlag().hashCode());
		result = 37
				* result
				+ (getSetGillnetFlag() == null ? 0 : this.getSetGillnetFlag()
						.hashCode());
		result = 37
				* result
				+ (getHandTrollFlag() == null ? 0 : this.getHandTrollFlag()
						.hashCode());
		result = 37
				* result
				+ (getLonglineFlag() == null ? 0 : this.getLonglineFlag()
						.hashCode());
		result = 37
				* result
				+ (getSingleOtterTrawlFlag() == null ? 0 : this
						.getSingleOtterTrawlFlag().hashCode());
		result = 37
				* result
				+ (getFishwheelFlag() == null ? 0 : this.getFishwheelFlag()
						.hashCode());
		result = 37
				* result
				+ (getPotGearFlag() == null ? 0 : this.getPotGearFlag()
						.hashCode());
		result = 37
				* result
				+ (getRingNetFlag() == null ? 0 : this.getRingNetFlag()
						.hashCode());
		result = 37
				* result
				+ (getDiveGearFlag() == null ? 0 : this.getDiveGearFlag()
						.hashCode());
		result = 37
				* result
				+ (getPowerTrollFlag() == null ? 0 : this.getPowerTrollFlag()
						.hashCode());
		result = 37
				* result
				+ (getBeamTrawlFlag() == null ? 0 : this.getBeamTrawlFlag()
						.hashCode());
		result = 37
				* result
				+ (getDredgeFlag() == null ? 0 : this.getDredgeFlag()
						.hashCode());
		result = 37
				* result
				+ (getDinglebarFlag() == null ? 0 : this.getDinglebarFlag()
						.hashCode());
		result = 37 * result
				+ (getJigFlag() == null ? 0 : this.getJigFlag().hashCode());
		result = 37
				* result
				+ (getDoubleOtterTrawl() == null ? 0 : this
						.getDoubleOtterTrawl().hashCode());
		result = 37
				* result
				+ (getHearingGillnetFlag() == null ? 0 : this
						.getHearingGillnetFlag().hashCode());
		result = 37
				* result
				+ (getPairTrawlFlag() == null ? 0 : this.getPairTrawlFlag()
						.hashCode());
		result = 37
				* result
				+ (getOtherGearFlag() == null ? 0 : this.getOtherGearFlag()
						.hashCode());
		result = 37
				* result
				+ (getHomeportCity() == null ? 0 : this.getHomeportCity()
						.hashCode());
		result = 37
				* result
				+ (getHomeportState() == null ? 0 : this.getHomeportState()
						.hashCode());
		result = 37
				* result
				+ (getRegistrationType() == null ? 0 : this
						.getRegistrationType().hashCode());
		result = 37
				* result
				+ (getCoastGuardNumber() == null ? 0 : this
						.getCoastGuardNumber().hashCode());
		result = 37
				* result
				+ (getVesselName() == null ? 0 : this.getVesselName()
						.hashCode());
		result = 37
				* result
				+ (getForeignFlagIndicator() == null ? 0 : this
						.getForeignFlagIndicator().hashCode());
		result = 37 * result
				+ (getHullId() == null ? 0 : this.getHullId().hashCode());
		result = 37
				* result
				+ (getSalmonTrollReg() == null ? 0 : this.getSalmonTrollReg()
						.hashCode());
		result = 37
				* result
				+ (getSalmonTrollDate() == null ? 0 : this.getSalmonTrollDate()
						.hashCode());
		result = 37
				* result
				+ (getSalmonRegArea() == null ? 0 : this.getSalmonRegArea()
						.hashCode());
		result = 37
				* result
				+ (getPermitSerial1() == null ? 0 : this.getPermitSerial1()
						.hashCode());
		result = 37
				* result
				+ (getPermitSerial2() == null ? 0 : this.getPermitSerial2()
						.hashCode());
		result = 37
				* result
				+ (getPermitHolderFileNumber() == null ? 0 : this
						.getPermitHolderFileNumber().hashCode());
		result = 37
				* result
				+ (getTransporterFlag() == null ? 0 : this.getTransporterFlag()
						.hashCode());
		result = 37 * result
				+ (getFRfee() == null ? 0 : this.getFRfee().hashCode());
		result = 37
				* result
				+ (getXRenewalYear() == null ? 0 : this.getXRenewalYear()
						.hashCode());
		result = 37
				* result
				+ (getRenewalStatus() == null ? 0 : this.getRenewalStatus()
						.hashCode());
		result = 37
				* result
				+ (getConfirmationCode() == null ? 0 : this
						.getConfirmationCode().hashCode());
		return result;
	}

}
